// Generates src/fonts.css and src/assets/fonts/*.woff2 from Google Fonts.
//
//   node scripts/fetch-fonts.ts
//
// The site loads Manrope and JetBrains Mono from fonts.gstatic.com, which is
// the fastest CDN for them, but not through Google's stylesheet: each
// @font-face rule here names the gstatic file first and a copy of the same
// file in src/assets/fonts second. Browsers try the sources in order, so when
// gstatic is unreachable the self-hosted copy is used and the typography does
// not change. Dropping the googleapis.com stylesheet also removes one
// render-blocking cross-origin request.
//
// The unicode-range subsets and file URLs are whatever Google serves to a
// current browser; rerun this when changing the families or weights below,
// and commit the results. The URLs are versioned (…/v15/…) and stay valid.
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";

const families = [
  { family: "Manrope", axis: "wght@400..800" },
  { family: "JetBrains Mono", axis: "wght@400..500" },
];

const ASSETS = new URL("../src/assets/fonts/", import.meta.url);
const CSS = new URL("../src/fonts.css", import.meta.url);

const query = families
  .map(({ family, axis }) => `family=${family.replace(/ /g, "+")}:${axis}`)
  .join("&");
const stylesheet = `https://fonts.googleapis.com/css2?${query}&display=swap`;

// Google serves woff2 with unicode-range subsets only to browsers it knows.
const response = await fetch(stylesheet, {
  headers: {
    "user-agent":
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36",
  },
});
if (!response.ok) throw new Error(`${stylesheet}: HTTP ${response.status}`);
const css = await response.text();

type Face = {
  subset: string;
  family: string;
  style: string;
  weight: string;
  url: string;
  unicodeRange: string;
};

const faces: Face[] = [];
const block = /\/\* (?<subset>[\w-]+) \*\/\s*@font-face \{(?<body>[^}]*)\}/g;
for (const match of css.matchAll(block)) {
  const subset = match.groups?.["subset"] ?? "";
  const body = match.groups?.["body"] ?? "";
  const prop = (name: string) => new RegExp(`${name}:\\s*([^;]+);`).exec(body)?.[1]?.trim() ?? "";
  const url = /url\(([^)]+)\)/.exec(prop("src"))?.[1];
  if (!url) throw new Error(`no url() in ${subset} block:\n${body}`);
  faces.push({
    subset,
    family: prop("font-family").replace(/^'|'$/g, ""),
    style: prop("font-style"),
    weight: prop("font-weight"),
    url,
    unicodeRange: prop("unicode-range"),
  });
}
if (faces.length === 0) throw new Error("no @font-face blocks found in Google's stylesheet");

await rm(ASSETS, { recursive: true, force: true });
await mkdir(ASSETS, { recursive: true });

const rules: string[] = [];
for (const face of faces) {
  const file = `${face.family.toLowerCase().replace(/ /g, "-")}-${face.subset}.woff2`;
  const font = await fetch(face.url);
  if (!font.ok) throw new Error(`${face.url}: HTTP ${font.status}`);
  await writeFile(new URL(file, ASSETS), Buffer.from(await font.arrayBuffer()));
  rules.push(
    [
      `/* ${face.family} ${face.subset} */`,
      "@font-face {",
      `  font-family: "${face.family}";`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      "  font-display: swap;",
      "  src:",
      `    url(${face.url}) format("woff2"),`,
      `    url(./assets/fonts/${file}) format("woff2");`,
      `  unicode-range: ${face.unicodeRange};`,
      "}",
    ].join("\n"),
  );
}

const header = [
  "/*",
  " * Generated by scripts/fetch-fonts.ts — do not edit by hand.",
  " *",
  " * Each face is loaded from fonts.gstatic.com first and from the copy in",
  " * assets/fonts/ if that fails, so the site keeps its typefaces when the",
  " * CDN is unreachable.",
  ` * Source: ${stylesheet}`,
  " */",
  "",
].join("\n");
await writeFile(CSS, header + rules.join("\n\n") + "\n");

const written = await readdir(ASSETS);
console.log(
  `${faces.length} @font-face rules → src/fonts.css, ${written.length} files → src/assets/fonts/`,
);
