/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsFuugaRouteImport } from './routes/projects/fuuga'
import { Route as ProjectsQuantumRouteImport } from './routes/projects/quantum'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFuugaRoute = ProjectsFuugaRouteImport.update({
  id: '/projects/fuuga',
  path: '/projects/fuuga',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsQuantumRoute = ProjectsQuantumRouteImport.update({
  id: '/projects/quantum',
  path: '/projects/quantum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/fuuga': typeof ProjectsFuugaRoute
  '/projects/quantum': typeof ProjectsQuantumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/fuuga': typeof ProjectsFuugaRoute
  '/projects/quantum': typeof ProjectsQuantumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/fuuga': typeof ProjectsFuugaRoute
  '/projects/quantum': typeof ProjectsQuantumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/fuuga' | '/projects/quantum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/fuuga' | '/projects/quantum'
  id: '__root__' | '/' | '/projects/fuuga' | '/projects/quantum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsFuugaRoute: typeof ProjectsFuugaRoute
  ProjectsQuantumRoute: typeof ProjectsQuantumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/fuuga': {
      id: '/projects/fuuga'
      path: '/projects/fuuga'
      fullPath: '/projects/fuuga'
      preLoaderRoute: typeof ProjectsFuugaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/quantum': {
      id: '/projects/quantum'
      path: '/projects/quantum'
      fullPath: '/projects/quantum'
      preLoaderRoute: typeof ProjectsQuantumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsFuugaRoute: ProjectsFuugaRoute,
  ProjectsQuantumRoute: ProjectsQuantumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
